### ISSUE TITLE
Pool

### ISSUE THREAD

**Issue by BaikalMine** [JKKGBE/open-zcash-pool-old#1]
Project closed?

**Comment by JKKGBE** [comment]
Nope, it’ll be back in 1-2 weeks. Should be more or less done by end of september.

**Comment by JKKGBE** [comment]
@BaikalMine Release postponed to EOY at the latest.

**Comment by JKKGBE** [comment]
This repo is deprecated.
Current repo: https://github.com/JKKGBE/open-zcash-pool
